# Generated by Django 5.2.7 on 2026-09-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_letter_file',
            field=models.FileField(blank=True, help_text='PDF offer letter generated for internship offers', null=True, upload_to='offer_letters/'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('selected', 'Selected'), ('offered', 'Offer Extended'), ('accepted', 'Accepted'), ('rejected', 'Not Selected')], default='applied', max_length=25),
        ),
    ]
