# Generated by Django 5.2.7 on 2026-09-22 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time Job'), ('part_time', 'Part-time Job'), ('internship', 'Internship'), ('contract', 'Contract / Freelance')], default='full_time', max_length=20)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote / Work From Home'), ('hybrid', 'Hybrid'), ('on_site', 'On-Site / Office')], default='remote', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('experience_level', models.CharField(choices=[('intern', 'Internship / Student (0 years)'), ('entry', 'Entry Level / Fresher (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5-8 years)'), ('lead', 'Lead / Principal (8+ years)')], default='entry', max_length=20)),
                ('min_experience_years', models.IntegerField(default=0)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_salary_negotiable', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
