# Generated by Django 5.2.7 on 2026-09-23 14:23
# Amended: de-duplicate existing email addresses before adding the unique constraint.

from django.db import migrations, models


def deduplicate_emails(apps, schema_editor):
    """
    Before enforcing unique emails, patch any duplicate rows so they don't
    block the migration.  Duplicates are renamed to:
        original+_dup<id>@domain
    This keeps the row but makes the email unique so the constraint can be added.
    Admins can then clean up the data manually afterwards.
    """
    User = apps.get_model('accounts', 'User')
    from collections import Counter

    # Find emails that appear more than once (case-insensitive)
    all_emails = list(User.objects.values_list('id', 'email'))
    email_count = Counter(e.lower() for _, e in all_emails)
    duplicated = {e for e, c in email_count.items() if c > 1}

    for email_lower in duplicated:
        users_with_email = list(
            User.objects.filter(email__iexact=email_lower).order_by('date_joined')
        )
        # Keep the oldest (first) account as-is; rename the rest
        for dup_user in users_with_email[1:]:
            local, _, domain = dup_user.email.partition('@')
            new_email = f"{local}_dup{dup_user.pk}@{domain}"
            dup_user.email = new_email
            dup_user.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Step 1: fix duplicate data so the unique constraint can be applied
        migrations.RunPython(deduplicate_emails, migrations.RunPython.noop),
        # Step 2: apply the unique constraint
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                error_messages={'unique': 'An account with this email address already exists.'},
                max_length=254,
                unique=True,
                verbose_name='email address',
            ),
        ),
    ]
