# Generated by Django 5.2.7 on 2026-09-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('website', models.URLField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='Technology', max_length=120)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees (Startup)'), ('11-50', '11-50 employees (Small)'), ('51-200', '51-200 employees (Medium)'), ('201-1000', '201-1000 employees (Mid-Enterprise)'), ('1000+', '1000+ employees (Large Enterprise)')], default='51-200', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
